config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "lists", to: "lists#index"
  get "lists/new", to: "lists#new"
  post "lists", to: "lists#create"
  get "lists/:id", to: "lists#show", as: :list
  get "movies", to: "movies#index"
  get "movies/:id", to: "movies#show"

  get "lists/:list_id/bookmarks/new", to: "bookmarks#new"
  post "lists/:list_id/bookmarks", to: "bookmarks#create", as: :list_bookmarks
  #A user can delete a bookmark from a list. How can we make a delete link again?
  delete "bookmarks/:id", to: "bookmarks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: {minimum: 5}
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true
  validates :overview, presence: true
  validates :title, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    @bookmark.save
    redirect_to list_path(@list)
  end
  

  def destroy
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @lists = List.find(params[:id])
  end

  def new
    @lists = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to list_path(@list)
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/destroy.html.erb
<h1>Bookmarks#destroy</h1>
<p>Find me in app/views/bookmarks/destroy.html.erb</p>

app/views/bookmarks/new.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie%>
  <%= f.submit "Add Movie", class: "btn btn-primary"%>
<% end %>


<!--- f.input :movie_id, collection: Movie.all --->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="navbar-lewagon"></div>
<div class="heading">
  <h1>Movie Listing</h1>
  <p><%=link_to "new list", lists_new_path%></p>
</div>

<div class= "container">
  <ul class="cards_list">
    <%@lists.each do |list|%>
    <div class="card"><li><%= link_to "#{list.name}", list_path(list.id), :class => "card_link" %></li></div>
    <%end%>
  </ul>
</div>

app/views/lists/new.html.erb
<%= simple_form_for [ @lists ] do |f| %>
  <%= f.input :name %>
  <%= f.submit "Submit list", class: "btn btn-primary" %>
<% end %>

app/views/lists/show.html.erb
<div class="heading">
  <h1><%=@lists.name%></h1>
  <p><%= link_to "List menu", lists_path%></p>
</div>

<div class = container>
  <ul class = cards_list><%@lists.movies.each do |m|%>
    <li class = "movie_card">
      <div>
        <%=image_tag "#{m.poster_url}", alt:"poster", :class => "poster"%>
        <%=m.title %>
      </div>
    </li>
    <%end%>
  </ul>
</div>  